name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissor:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissor:latest ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissor:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissor:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rock-paper-scissor:${{ github.sha }}
